use super::{game::*, types::*};

/// DAAD Code Generator
/// Converts visual game data into DRC-compatible DAAD source code (.SCE format)
pub struct DaadCodeGenerator;

impl DaadCodeGenerator {
    /// Generate complete DAAD source code from visual game
    /// Follows DRC specification EXACTLY - section order matters!
    pub fn generate(game: &DaadGame) -> String {
        let mut code = String::new();

        // Header with comments and #define statements
        code.push_str(&Self::generate_header(game));

        // CRITICAL: DRC requires strict section ordering!
        // 1. /CTL - Control section (null character)
        code.push_str(&Self::generate_control_section());

        // 2. /VOC - Vocabulary
        code.push_str(&Self::generate_vocabulary(&game.vocabulary));

        // 3. /STX - System Messages (0-62)
        code.push_str(&Self::generate_system_messages());

        // 4. /MTX - Custom Messages
        code.push_str(&Self::generate_messages(&game.messages));

        // 5. /OTX - Object Texts
        code.push_str(&Self::generate_object_texts(&game.objects));

        // 6. /LTX - Location Texts
        code.push_str(&Self::generate_location_texts(&game.locations));

        // 7. /CON - Connections
        code.push_str(&Self::generate_connections(&game.locations));

        // 8. /OBJ - Object Definitions
        code.push_str(&Self::generate_object_definitions(&game.objects));

        // 9-12. /PRO 0-3 - Process Tables
        code.push_str(&Self::generate_processes(game));

        code
    }

    fn generate_header(game: &DaadGame) -> String {
        format!(
            "; ========================================\n\
             ; {}\n\
             ; by {}\n\
             ; Version: {}\n\
             ; Generated by DAAD Bevy Builder\n\
             ; ========================================\n\
             \n\
             ; System flags 0-63\n\
             #define fDark               0\n\
             #define fObjectsCarried     1\n\
             #define fDarkF              28\n\
             #define fGFlags             29\n\
             #define fScore              30\n\
             #define fTurns              31\n\
             #define fTurnsHi            32\n\
             #define fVerb               33\n\
             #define fNoun               34\n\
             #define fAdject1            35\n\
             #define fAdverb             36\n\
             #define fMaxCarr            37\n\
             #define fPlayer             38\n\
             #define fPrep               43\n\
             #define fNoun2              44\n\
             #define fAdject2            45\n\
             #define fCPronounNoun       46\n\
             #define fCPronounAdject     47\n\
             #define fTimeout            48\n\
             #define fTimeoutFlags       49\n\
             #define fDoallObjNo         50\n\
             #define fRefObject          51\n\
             #define fStrength           52\n\
             #define fObjFlags           53\n\
             #define fRefObjLoc          54\n\
             #define fRefObjWeight       55\n\
             #define fRefObjIsContainer  56\n\
             #define fRefObjisWearable   57\n\
             #define fRefObjAttr1        58\n\
             #define fRefObjAttr2        59\n\
             #define fInkeyKey1          60\n\
             #define fInkeyKey2          61\n\
             #define fScreenMode         62\n\
             #define fCurrentWindow      63\n\
             \n\n",
            game.title, game.author, game.version
        )
    }

    fn generate_control_section() -> String {
        String::from(
            ";------------------------------------------------------------------------------\n\
             /CTL    ;Control Section (null char is an underline)\n\
             _       \n\
             \n\n"
        )
    }

    fn generate_vocabulary(vocab: &[VocabEntry]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /VOC    ;Vocabulary\n\n"
        );

        // Separate vocabulary by type
        let mut movements: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Noun) && v.id < 14)
            .collect();
        let mut nouns: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Noun) && v.id >= 14)
            .collect();
        let mut verbs: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Verb))
            .collect();
        let mut adjectives: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Adjective))
            .collect();
        let mut adverbs: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Adverb))
            .collect();
        let mut prepositions: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Preposition))
            .collect();
        let mut pronouns: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Pronoun))
            .collect();
        let mut conjugations: Vec<_> = vocab.iter()
            .filter(|v| matches!(v.word_type, VocabType::Conjugation))
            .collect();

        // Sort each group by ID
        movements.sort_by_key(|v| v.id);
        nouns.sort_by_key(|v| v.id);
        verbs.sort_by_key(|v| v.id);
        adjectives.sort_by_key(|v| v.id);
        adverbs.sort_by_key(|v| v.id);
        prepositions.sort_by_key(|v| v.id);
        pronouns.sort_by_key(|v| v.id);
        conjugations.sort_by_key(|v| v.id);

        // Movements (nouns < 14)
        if !movements.is_empty() {
            code.push_str(";                       Movements ie verbs and nouns < 14\n");
            for v in movements {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Nouns (<20 can be verbs, <50 are proper nouns)
        if !nouns.is_empty() {
            code.push_str(";                       Nouns   <20 means can be used as verbs\n");
            code.push_str(";                               <50 means a proper noun ie not an 'IT'\n");
            for v in nouns {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Verbs
        if !verbs.is_empty() {
            code.push_str(";                       Verbs\n");
            for v in verbs {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Adjectives
        if !adjectives.is_empty() {
            code.push_str(";                               Adjectives\n");
            for v in adjectives {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Adverbs
        if !adverbs.is_empty() {
            code.push_str(";                               Adverbs\n");
            for v in adverbs {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Prepositions
        if !prepositions.is_empty() {
            code.push_str(";                               Prepositions\n");
            for v in prepositions {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Pronouns
        if !pronouns.is_empty() {
            code.push_str(";                               Pronouns\n");
            for v in pronouns {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        // Conjugations
        if !conjugations.is_empty() {
            code.push_str(";                               Conjugations\n");
            for v in conjugations {
                code.push_str(&format!("{:<8}{:<8}{}\n",
                    v.word.to_uppercase(),
                    v.id,
                    v.word_type.as_str()
                ));
            }
            code.push('\n');
        }

        code.push('\n');
        code
    }

    fn generate_system_messages() -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /STX    ;System Message Texts\n"
        );

        // Default DAAD system messages (0-62) from BLANK_EN.DSF
        let default_messages = [
            "It's too dark to see anything.",
            "I can also see: ",
            "#nWhat now?",
            "#nWhat next?",
            "#nWhat should I do now?",
            "#nWhat should I do next?",
            "#nI was not able to understand any of that.  Please try again.",
            "#nI can't go in that direction.",
            "I can't do that.#n",
            "I have with me:#n",
            "I am wearing:#n",
            "", // Spare
            "Are you sure? ",
            "Would you like another go? ",
            "", // Spare
            "OK.#n",
            "Press any key to continue.#n",
            "", // You have taken
            "", // \sturn
            "", // s
            "", // .[CR]
            "", // You have scored
            "", // %[CR]
            "I'm not wearing one of those.#n",
            "I can't.  I'm wearing the _.",
            "I already have the _.",
            "There isn't one of those here.",
            "I can't carry any more things.",
            "I don't have one of those.",
            "I'm already wearing the _.",
            "Y", // One upper case character only
            "N", // One upper case character only
            "More...",
            "#n>",
            "", // Spare
            "#nTime passes...#n",
            "I now have the _.#n",
            "I'm now wearing the _.#n",
            "I've removed the _.#n",
            "I've dropped the _.#n",
            "I can't wear the _.#n",
            "I can't remove the _.#n",
            "I can't remove the _.  My hands are full.#n",
            "The _ weighs too much for me.#n",
            "#nThe _ is in the ",
            "The _ isn't in the ",
            ", ",
            " and ",
            ".#n",
            "I don't have the _.#n",
            "I'm not wearing the _.#n",
            ".#n",
            "There isn't one of those in the ",
            "Nothing.#n",
            "T", // Letter for Tape
            "D", // Disc
            "Drive not ready - press any key to retry.#n",
            "I/O Error.#n",
            "Disc or Directory may be full.",
            "Invalid filename.",
            "Type in name of file:",
            "Start tape.#n",
            "Tape or Disc?",
        ];

        for (i, msg) in default_messages.iter().enumerate() {
            code.push_str(&format!("/{} \"{}\"\n", i, msg));
        }

        code.push_str("\n\n");
        code
    }

    fn generate_messages(messages: &[String]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /MTX    ;Message Texts\n"
        );

        if messages.is_empty() {
            code.push_str("/0 \"\"\n");
        } else {
            for (i, msg) in messages.iter().enumerate() {
                code.push_str(&format!("/{} \"{}\"\n", i, msg));
            }
        }

        code.push_str("\n\n");
        code
    }

    fn generate_object_texts(objects: &[Object]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /OTX    ;Object Texts\n"
        );

        if objects.is_empty() {
            code.push_str("/0 \"\"\n");
        } else {
            for obj in objects {
                code.push_str(&format!("/{} \"{}\"\n", obj.id, obj.description));
            }
        }

        code.push_str("\n\n");
        code
    }

    fn generate_location_texts(locations: &[Location]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /LTX    ;Location Texts\n"
        );

        if locations.is_empty() {
            code.push_str("/0 \"Empty location\"\n");
        } else {
            for loc in locations {
                code.push_str(&format!("/{} \"{}\"\n", loc.id, loc.description));
            }
        }

        code.push_str("\n\n");
        code
    }

    fn generate_connections(locations: &[Location]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /CON    ;Connections\n"
        );

        if locations.is_empty() {
            code.push_str("/0\n");
        } else {
            for loc in locations {
                code.push_str(&format!("/{}\n", loc.id));
                for conn in &loc.connections {
                    code.push_str(&format!("{} {}\n",
                        conn.direction.as_short_str(),
                        conn.target_location
                    ));
                }
            }
        }

        code.push_str("\n\n");
        code
    }

    fn generate_object_definitions(objects: &[Object]) -> String {
        let mut code = String::from(
            ";------------------------------------------------------------------------------\n\
             /OBJ    ;Object Definitions\n\
             ;obj  starts  weight    c w  5 4 3 2 1 0 9 8 7 6 5 4 3 2 1 0    noun   adjective\n\
             ;num    at\n"
        );

        for obj in objects {
            let location = match obj.location {
                ObjectLocation::Location(id) => id.to_string(),
                ObjectLocation::Carried => "CARRIED".to_string(),
                ObjectLocation::Worn => "WORN".to_string(),
                ObjectLocation::Limbo => "LIMBO".to_string(),
                ObjectLocation::Inside(_) => "LIMBO".to_string(), // Containers handled differently
            };

            let container_flag = if obj.is_container { "*" } else { "_" };
            let wearable_flag = if obj.is_wearable { "*" } else { "_" };

            // Attribute bits (16 bits, all unset for now)
            let attr_bits = "_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _";

            let adjective = if obj.adjective.is_empty() { "_" } else { &obj.adjective };

            code.push_str(&format!(
                "/{:<8}{:<8}{:<10}{} {}  {}    {:<7}{}\n",
                obj.id,
                location,
                obj.weight,
                container_flag,
                wearable_flag,
                attr_bits,
                obj.noun.to_uppercase(),
                adjective.to_uppercase()
            ));
        }

        code.push_str("\n\n");
        code
    }

    fn generate_processes(game: &DaadGame) -> String {
        let mut code = String::new();

        // Generate each process table (0-3)
        for process_num in 0..4 {
            let process_type = ProcessTable::from_num(process_num);
            code.push_str(&format!(
                ";------------------------------------------------------------------------------\n\
                 /PRO {}       ;{}\n",
                process_num,
                process_type.description()
            ));

            // Get rules for this process
            let process_rules: Vec<_> = game
                .rules
                .iter()
                .filter(|r| r.process == process_type && r.enabled)
                .collect();

            if process_rules.is_empty() {
                // Add minimal default entry
                code.push_str("\n> _       _\n\n");
            } else {
                for rule in process_rules {
                    code.push_str(&Self::generate_rule(rule, game));
                    code.push('\n');
                }
            }
        }

        code
    }

    fn generate_rule(rule: &Rule, game: &DaadGame) -> String {
        let mut code = String::new();

        // Comment with rule name
        code.push_str(&format!("\n; {}\n", rule.name));

        // First line: > VERB NOUN CONDITION(s)
        // TODO: Extract verb/noun from rule - for now use wildcards
        let verb = "_";
        let noun = "_";

        code.push_str(&format!("> {:<7} {:<7}", verb, noun));

        // Add first condition on same line
        if !rule.conditions.is_empty() {
            code.push(' ');
            code.push_str(&Self::generate_condition(&rule.conditions[0], game));

            // Add remaining conditions on indented lines
            for condition in rule.conditions.iter().skip(1) {
                code.push('\n');
                code.push_str("                ");
                code.push_str(&Self::generate_condition(condition, game));
            }
        }

        code.push('\n');

        // Actions on indented lines
        for action in &rule.actions {
            code.push_str("                ");
            code.push_str(&Self::generate_action(action, game));
            code.push('\n');
        }

        code
    }

    fn generate_condition(condition: &Condition, game: &DaadGame) -> String {
        match &condition.condition_type {
            ConditionType::PlayerAt { location_id } => {
                format!("AT {}", location_id)
            }
            ConditionType::PlayerNotAt { location_id } => {
                format!("NOTAT {}", location_id)
            }
            ConditionType::ObjectPresent { object_id } => {
                format!("PRESENT {}", object_id)
            }
            ConditionType::ObjectCarried { object_id } => {
                format!("CARRIED {}", object_id)
            }
            ConditionType::ObjectWorn { object_id } => {
                format!("WORN {}", object_id)
            }
            ConditionType::ObjectAt {
                object_id,
                location_id,
            } => {
                format!("ISAT {} {}", object_id, location_id)
            }
            ConditionType::FlagEquals { flag_id, value } => {
                format!("EQ {} {}", flag_id, value)
            }
            ConditionType::FlagGreaterThan { flag_id, value } => {
                format!("GT {} {}", flag_id, value)
            }
            ConditionType::FlagLessThan { flag_id, value } => {
                format!("LT {} {}", flag_id, value)
            }
            ConditionType::FlagZero { flag_id } => {
                format!("ZERO {}", flag_id)
            }
            ConditionType::VerbIs { verb } => {
                format!("VERB {}", verb)
            }
            ConditionType::NounIs { noun } => {
                format!("NOUN {}", noun)
            }
            ConditionType::IsFirstTurn => {
                format!("EQ {} 0", 31) // fTurns == 0
            }
            ConditionType::TurnCountGreaterThan { turns } => {
                format!("GT {} {}", 31, turns) // fTurns > turns
            }
            ConditionType::ScoreGreaterThan { score } => {
                format!("GT {} {}", 30, score) // fScore > score
            }
        }
    }

    fn generate_action(action: &Action, game: &DaadGame) -> String {
        match &action.action_type {
            ActionType::ShowMessage { text } => {
                // Use MES for message index, or inline for direct text
                format!("MESSAGE \"{}\"", text)
            }
            ActionType::ShowLocationDescription => {
                "DESC @fPlayer".to_string()
            }
            ActionType::ClearScreen => {
                "CLS".to_string()
            }
            ActionType::GetObject { object_id } => {
                format!("GET {}", object_id)
            }
            ActionType::DropObject { object_id } => {
                format!("DROP {}", object_id)
            }
            ActionType::WearObject { object_id } => {
                format!("WEAR {}", object_id)
            }
            ActionType::RemoveObject { object_id } => {
                format!("REMOVE {}", object_id)
            }
            ActionType::MoveObject {
                object_id,
                to_location,
            } => {
                let loc_num = to_location.to_daad_location();
                format!("PLACE {} {}", object_id, loc_num)
            }
            ActionType::SetFlag { flag_id, value } => {
                format!("LET {} {}", flag_id, value)
            }
            ActionType::IncrementFlag { flag_id } => {
                format!("PLUS {} 1", flag_id)
            }
            ActionType::DecrementFlag { flag_id } => {
                format!("MINUS {} 1", flag_id)
            }
            ActionType::GoToLocation { location_id } => {
                format!("GOTO {}", location_id)
            }
            ActionType::EndTurn => {
                "DONE".to_string()
            }
            ActionType::ContinueProcessing => {
                "NOTDONE".to_string()
            }
            ActionType::SkipRules { count } => {
                format!("SKIP {}", count)
            }
            ActionType::AddScore { points } => {
                format!("PLUS {} {}", 30, points) // fScore += points
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_game() {
        let game = DaadGame::default();
        let code = DaadCodeGenerator::generate(&game);

        // Check all required sections exist in correct order
        let ctl_pos = code.find("/CTL").expect("Missing /CTL section");
        let voc_pos = code.find("/VOC").expect("Missing /VOC section");
        let stx_pos = code.find("/STX").expect("Missing /STX section");
        let mtx_pos = code.find("/MTX").expect("Missing /MTX section");
        let otx_pos = code.find("/OTX").expect("Missing /OTX section");
        let ltx_pos = code.find("/LTX").expect("Missing /LTX section");
        let con_pos = code.find("/CON").expect("Missing /CON section");
        let obj_pos = code.find("/OBJ").expect("Missing /OBJ section");
        let pro0_pos = code.find("/PRO 0").expect("Missing /PRO 0 section");

        // Verify correct ordering
        assert!(ctl_pos < voc_pos, "CTL must come before VOC");
        assert!(voc_pos < stx_pos, "VOC must come before STX");
        assert!(stx_pos < mtx_pos, "STX must come before MTX");
        assert!(mtx_pos < otx_pos, "MTX must come before OTX");
        assert!(otx_pos < ltx_pos, "OTX must come before LTX");
        assert!(ltx_pos < con_pos, "LTX must come before CON");
        assert!(con_pos < obj_pos, "CON must come before OBJ");
        assert!(obj_pos < pro0_pos, "OBJ must come before PRO 0");
    }

    #[test]
    fn test_system_messages_count() {
        let game = DaadGame::default();
        let code = DaadCodeGenerator::generate(&game);

        // Should have 63 system messages (0-62)
        let stx_section = code.split("/STX").nth(1).unwrap().split("/MTX").nth(0).unwrap();
        let message_count = stx_section.matches("/").filter(|s| !s.is_empty()).count();
        assert_eq!(message_count, 63, "Should have 63 system messages (0-62)");
    }

    #[test]
    fn test_vocabulary_format() {
        let mut game = DaadGame::default();
        game.vocabulary.push(VocabEntry {
            word: "test".to_string(),
            word_type: VocabType::Verb,
            id: 20,
        });

        let code = DaadCodeGenerator::generate(&game);

        // Check format: "WORD    ID      type"
        assert!(code.contains("TEST    20      verb"),
            "Vocabulary should be formatted as 'WORD    ID      type'");
    }
}
