use super::{game::*, types::*};

/// DAAD Code Generator
/// Converts visual game data into DAAD source code
pub struct DaadCodeGenerator;

impl DaadCodeGenerator {
    /// Generate complete DAAD source code from visual game
    pub fn generate(game: &DaadGame) -> String {
        let mut code = String::new();

        // Header
        code.push_str(&Self::generate_header(game));

        // Locations
        code.push_str(&Self::generate_locations(&game.locations));

        // Objects
        code.push_str(&Self::generate_objects(&game.objects));

        // Messages
        code.push_str(&Self::generate_messages(&game.messages));

        // Vocabulary
        code.push_str(&Self::generate_vocabulary(&game.vocabulary));

        // Process tables (PRO 0-3)
        code.push_str(&Self::generate_processes(game));

        code
    }

    fn generate_header(game: &DaadGame) -> String {
        format!(
            "; ========================================\n\
             ; {}\n\
             ; by {}\n\
             ; Version: {}\n\
             ; Generated by DAAD Bevy Builder\n\
             ; ========================================\n\n",
            game.title, game.author, game.version
        )
    }

    fn generate_locations(locations: &[Location]) -> String {
        let mut code = String::from("/LTX ; Location Texts\n\n");

        for loc in locations {
            code.push_str(&format!("; Location {}: {}\n", loc.id, loc.name));
            if loc.is_dark {
                code.push_str("; DARK LOCATION\n");
            }
            code.push_str(&format!("{}\n", loc.description));

            // Connections (as comments for now - actual connections are in /CON section)
            if !loc.connections.is_empty() {
                code.push_str("; Exits:\n");
                for conn in &loc.connections {
                    code.push_str(&format!(
                        ";   {} -> Location {}\n",
                        conn.direction.as_str(),
                        conn.target_location
                    ));
                }
            }

            code.push('\n');
        }

        code
    }

    fn generate_objects(objects: &[Object]) -> String {
        let mut code = String::from("/OTX ; Object Texts\n\n");

        for obj in objects {
            code.push_str(&format!("; Object {}: {} {}\n", obj.id, obj.adjective, obj.noun));
            code.push_str(&format!(
                "{} {} {}\n",
                obj.adjective, obj.noun, obj.description
            ));

            // Object properties as comments
            code.push_str(&format!("; Weight: {}\n", obj.weight));
            code.push_str(&format!("; Location: {:?}\n", obj.location));
            if obj.is_container {
                code.push_str("; Container\n");
            }
            if obj.is_wearable {
                code.push_str("; Wearable\n");
            }
            if !obj.is_takeable {
                code.push_str("; Not takeable\n");
            }
            code.push('\n');
        }

        code
    }

    fn generate_messages(messages: &[String]) -> String {
        let mut code = String::from("/MTX ; Messages\n\n");

        for (i, msg) in messages.iter().enumerate() {
            code.push_str(&format!("; Message {}\n", i));
            code.push_str(&format!("{}\n\n", msg));
        }

        code
    }

    fn generate_vocabulary(vocab: &[VocabEntry]) -> String {
        let mut code = String::from("/VOC ; Vocabulary\n\n");

        let mut verbs: Vec<_> = vocab.iter().filter(|v| v.word_type == VocabType::Verb).collect();
        let mut nouns: Vec<_> = vocab.iter().filter(|v| v.word_type == VocabType::Noun).collect();
        let mut adjectives: Vec<_> = vocab
            .iter()
            .filter(|v| v.word_type == VocabType::Adjective)
            .collect();

        verbs.sort_by_key(|v| v.id);
        nouns.sort_by_key(|v| v.id);
        adjectives.sort_by_key(|v| v.id);

        if !verbs.is_empty() {
            code.push_str("; Verbs\n");
            for v in verbs {
                code.push_str(&format!("{} ; {}\n", v.word, v.id));
            }
            code.push('\n');
        }

        if !nouns.is_empty() {
            code.push_str("; Nouns\n");
            for n in nouns {
                code.push_str(&format!("{} ; {}\n", n.word, n.id));
            }
            code.push('\n');
        }

        if !adjectives.is_empty() {
            code.push_str("; Adjectives\n");
            for a in adjectives {
                code.push_str(&format!("{} ; {}\n", a.word, a.id));
            }
            code.push('\n');
        }

        code
    }

    fn generate_processes(game: &DaadGame) -> String {
        let mut code = String::new();

        // Generate each process table
        for process_num in 0..4 {
            let process_type = ProcessTable::from_num(process_num);
            code.push_str(&format!(
                "/PRO {} ; {}\n\n",
                process_num,
                process_type.description()
            ));

            // Get rules for this process
            let process_rules: Vec<_> = game
                .rules
                .iter()
                .filter(|r| r.process == process_type && r.enabled)
                .collect();

            for rule in process_rules {
                code.push_str(&Self::generate_rule(rule, game));
                code.push('\n');
            }
        }

        code
    }

    fn generate_rule(rule: &Rule, game: &DaadGame) -> String {
        let mut code = String::new();

        code.push_str(&format!("; Rule: {}\n", rule.name));

        // Generate conditions
        if !rule.conditions.is_empty() {
            for condition in &rule.conditions {
                code.push_str(&Self::generate_condition(condition, game));
                code.push('\n');
            }
        }

        // Generate actions
        if !rule.actions.is_empty() {
            for action in &rule.actions {
                code.push_str(&Self::generate_action(action, game));
                code.push('\n');
            }
        }

        code
    }

    fn generate_condition(condition: &Condition, game: &DaadGame) -> String {
        match &condition.condition_type {
            ConditionType::PlayerAt { location_id } => {
                let loc_name = game
                    .get_location(*location_id)
                    .map(|l| l.name.as_str())
                    .unwrap_or("???");
                format!("AT {} ; {}", location_id, loc_name)
            }
            ConditionType::PlayerNotAt { location_id } => {
                format!("NOTAT {}", location_id)
            }
            ConditionType::ObjectPresent { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("PRESENT {} ; {}", object_id, obj_name)
            }
            ConditionType::ObjectCarried { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("CARRIED {} ; {}", object_id, obj_name)
            }
            ConditionType::ObjectWorn { object_id } => {
                format!("WORN {}", object_id)
            }
            ConditionType::ObjectAt {
                object_id,
                location_id,
            } => {
                format!("AT {} {}", object_id, location_id)
            }
            ConditionType::FlagEquals { flag_id, value } => {
                let flag_name = game
                    .get_flag(*flag_id)
                    .map(|f| f.name.as_str())
                    .unwrap_or("???");
                format!("EQ {} {} ; {}", flag_id, value, flag_name)
            }
            ConditionType::FlagGreaterThan { flag_id, value } => {
                format!("GT {} {}", flag_id, value)
            }
            ConditionType::FlagLessThan { flag_id, value } => {
                format!("LT {} {}", flag_id, value)
            }
            ConditionType::FlagZero { flag_id } => {
                format!("ZERO {}", flag_id)
            }
            ConditionType::VerbIs { verb } => {
                format!("VERB {}", verb)
            }
            ConditionType::NounIs { noun } => {
                format!("NOUN {}", noun)
            }
            ConditionType::IsFirstTurn => "TURNS 0".to_string(),
            ConditionType::TurnCountGreaterThan { turns } => {
                format!("TURNSGT {}", turns)
            }
            ConditionType::ScoreGreaterThan { score } => {
                format!("SCOREGT {}", score)
            }
        }
    }

    fn generate_action(action: &Action, game: &DaadGame) -> String {
        match &action.action_type {
            ActionType::ShowMessage { text } => {
                format!("MESSAGE \"{}\"", text)
            }
            ActionType::ShowLocationDescription => "DESC".to_string(),
            ActionType::ClearScreen => "CLS".to_string(),
            ActionType::GetObject { object_id } => {
                let obj_name = game
                    .get_object(*object_id)
                    .map(|o| o.name.as_str())
                    .unwrap_or("???");
                format!("GET {} ; {}", object_id, obj_name)
            }
            ActionType::DropObject { object_id } => {
                format!("DROP {}", object_id)
            }
            ActionType::WearObject { object_id } => {
                format!("WEAR {}", object_id)
            }
            ActionType::RemoveObject { object_id } => {
                format!("REMOVE {}", object_id)
            }
            ActionType::MoveObject {
                object_id,
                to_location,
            } => {
                let loc_num = to_location.to_daad_location();
                format!("PLACE {} {}", object_id, loc_num)
            }
            ActionType::SetFlag { flag_id, value } => {
                let flag_name = game
                    .get_flag(*flag_id)
                    .map(|f| f.name.as_str())
                    .unwrap_or("???");
                format!("LET {} {} ; {}", flag_id, value, flag_name)
            }
            ActionType::IncrementFlag { flag_id } => {
                format!("PLUS {} 1", flag_id)
            }
            ActionType::DecrementFlag { flag_id } => {
                format!("MINUS {} 1", flag_id)
            }
            ActionType::GoToLocation { location_id } => {
                let loc_name = game
                    .get_location(*location_id)
                    .map(|l| l.name.as_str())
                    .unwrap_or("???");
                format!("GOTO {} ; {}", location_id, loc_name)
            }
            ActionType::EndTurn => "DONE".to_string(),
            ActionType::ContinueProcessing => "NOTDONE".to_string(),
            ActionType::SkipRules { count } => {
                format!("SKIP {}", count)
            }
            ActionType::AddScore { points } => {
                format!("SCORE {}", points)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_empty_game() {
        let game = DaadGame::default();
        let code = DaadCodeGenerator::generate(&game);
        assert!(code.contains("/LTX"));
        assert!(code.contains("/OTX"));
        assert!(code.contains("/PRO 0"));
    }

    #[test]
    fn test_generate_simple_rule() {
        let mut game = DaadGame::default();
        let rule_id = game.add_rule("Test Rule", ProcessTable::Response);

        let rule = game.rules.get_mut(rule_id).unwrap();
        rule.conditions.push(Condition {
            id: 0,
            condition_type: ConditionType::PlayerAt { location_id: 0 },
        });
        rule.actions.push(Action {
            id: 0,
            action_type: ActionType::ShowMessage {
                text: "Hello!".to_string(),
            },
        });

        let code = DaadCodeGenerator::generate(&game);
        assert!(code.contains("AT 0"));
        assert!(code.contains("MESSAGE \"Hello!\""));
    }
}
